# Generated by Django 4.1.3 on 2022-12-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_description_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-date_created']},
        ),
    ]
