# Generated by Django 4.1.4 on 2022-12-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_product_image_2_product_image_3_product_image_4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_2",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_3",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_4",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
