# Generated by Django 4.1.4 on 2023-01-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_product_image_2_product_image_3_product_image_4"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_5",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_6",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
