# Generated by Django 4.1.4 on 2023-01-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_cart_products_delete_productorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_5",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image_6",
        ),
    ]
