# Generated by Django 4.1.4 on 2023-01-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_remove_product_image_5_remove_product_image_6"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_5",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_6",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
