# Generated by Django 4.1.4 on 2023-01-11 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_productorder_alter_cart_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="cart",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.cart"
            ),
        ),
    ]
