# Generated by Django 4.1.4 on 2023-01-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_productorder_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(related_name="products", to="main.product"),
        ),
        migrations.DeleteModel(
            name="ProductOrder",
        ),
    ]
