# Generated by Django 4.1.4 on 2023-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_store_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="pickup_station",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
