# Generated by Django 4.1.4 on 2023-02-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_rename_address_order_location_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="products_ordered",
            field=models.ManyToManyField(
                related_name="products_ordered", to="main.productorder"
            ),
        ),
    ]
