# Generated by Django 4.1.4 on 2023-02-01 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_alter_order_products_ordered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_placed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
