# Generated by Django 4.1.4 on 2023-02-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_placed",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="date_to_be_delivered",
            field=models.DateField(blank=True, null=True),
        ),
    ]
