# Generated by Django 4.1.4 on 2023-02-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_rename_logo_store_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="/store_logos/shop.jpg",
                null=True,
                upload_to="store_logos/",
            ),
        ),
    ]
