# Generated by Django 4.1.4 on 2023-02-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_alter_store_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="date_to_be_delivered",
            new_name="delivery_date",
        ),
    ]
