# Generated by Django 4.1.4 on 2023-02-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_rename_date_to_be_delivered_order_delivery_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="completed",
        ),
    ]
