# Generated by Django 4.1.4 on 2023-02-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0042_notification_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("ORDER UPDATE", "o"), ("NEW ORDER", "n")],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
