# Generated by Django 4.1.4 on 2023-02-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0043_alter_notification_options_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
