# Generated by Django 4.1.4 on 2023-02-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0044_alter_notification_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="details",
            field=models.JSONField(null=True),
        ),
    ]
