# Generated by Django 4.1.4 on 2023-02-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0045_notification_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="category",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
